version: "3.3"
services:
  solr:
    image: ${SERVICE_IMAGE}:${IMAGE_TAG:-dev}
    build:
      context: .
      labels:
        zenoss.zing.commit-sha: ${COMMIT_SHA:-none}
        zenoss.zing.pull-request: ${PULL_REQUEST:-none}
        zenoss.zing.branch_name: ${GIT_BRANCH:-none}
        zenoss.zing.build_number: ${BUILD_ID:-none}
        zenoss.zing.build_url: ${BUILD_URL:-none}
    command: init-solr.sh solr start -f -cloud
    environment:
      # ZK_HOST indicates the ZK nodes and optionally chroot
      # If not set, it indicates that embedded ZK should be used.
      #- ZK_HOST=zk1,zl2,zk3/solr
      # When using embedded zk, the zk chroot can still be specified
      # via the ZK_CHROOT variable.  Ignored otherwise. 
      - ZK_CHROOT=/solr

